### ISSUE TITLE
chktex not there

### ISSUE THREAD

**Issue by sils** [coala/docker-coala-base#1]

**Comment by sils** [comment]
I thought this is _not_ solved?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by fneu** [comment]
Chktex is installed and up and running at least on cli. The bear might 
still have an issue but it's not with chktex per se. I will add Issues soon 
for all the Tests that still fail so we can collect specific Info.

**Comment by sils** [comment]
ah fine :)

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/
