### ISSUE TITLE
Travis test

### ISSUE THREAD

**Issue by AbdealiLoKo** [coala/docker-coala-base#12]
It would be nice to make a travis file which uses the dockerfile to run tests.
Creating this because the PR https://github.com/coala-analyzer/docker-coala-base/pull/8 will close soon and it may get lost.

Something like:

``` https://github.com/coala-analyzer/docker-coala-base/pull/8https://github.com/coala-analyzer/docker-coala-base/pull/8
sudo: required

services:
  - docker

install:
  - docker build -f Dockerfile -t coala-docker-tag .
  - docker images

script:
  - docker run coala-docker-tag /bin/sh -c "cd /path/to/coala/git/clone; python3 -m pytest --cov"

notification:
  - false
```

**Comment by sils** [comment]
like it @fneu should be easy to do huh?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by AbdealiLoKo** [comment]
@fneu commenting on https://github.com/coala-analyzer/docker-coala-base/pull/8#issuecomment-229321686 here...

IIRC (based on some testing I did earlier), Travis builds have an internet speed of 8GBps and about 30GB data storage available. It allows around 40-60 mins of processing time. But, the travis CPU is really fast (8 core I think)

Also, circleci can do it in the `coala-bears` repo. i.e. if we disable cache, circleci does do all of this stuff in the CI environment anyway without timing out right ?

Conclusion: I'm fairly certain it can handle it. But the only way to know for sure is to try :)

**Comment by fneu** [comment]
Wow and I thought I have fast Internet :D Also my 1 hour clocks in on an 
dualcore i5, We should be fine with those specs. I'll clean up my branch 
and make a pull request today or tomorrow including Travis tests, promised.

Am 29. Juni 2016 12:51:27 nachm. schrieb AbdealiJK notifications@github.com:

**Comment by fneu** [comment]
Big drama with my girlfriend yesterday + unexpected job interview today (smalish). Busy this evening and need to review stuff for GitMate tonight so I will finish this stuff tomorrow.
