### ISSUE TITLE
CSharpBear needs mcs

### ISSUE THREAD

**Issue by jjweis** [coala/docker-coala-base#135]
I tried running CSharpLintBear through the container, got this error:

> The bear CSharpLintBear does not fulfill all requirements. 'mcs' is not installed.

I added a zypper line downloading **mono-devel** (per [here](http://www.mono-project.com/docs/getting-started/install/linux/#opensuse-and-sles) ) in my Dockerfile and it worked.

**Comment by jayvdb** [comment]
mono was intentionally removed in https://github.com/coala/docker-coala-base/issues/65 because that bear doesnt appear to be very useful, and the dependencies are huge.
See https://github.com/coala/coala-bears/issues/1185

If you are using the bear, please let us know which project is using it.

**Comment by jjweis** [comment]
Not a problem, I didn't see Issue #65 before. I can just use a fork with mono as part of a personal project.
