### ISSUE TITLE
Quick start for using as a Travis job

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#15]
It would be useful to provide a recipe for users to copy and paste into their `.travis.yml` to use this docker as a linter job, and possibly also for other CI engines that support dockers.

It should use auto-discovery as much as possible, so that the sample recipe works irrespective of the contents of the repository, and only needs to be tuned if the code is buggy, or they want to reduce the runtime by focusing coala on specific areas of the repo or types of files..

This may already exist in the documentation, in which case a link in this repos `README.md` would be sufficient.

We could go one step further and build a tool that automatically creates the `.travis.yml`, etc.

**Comment by sils** [comment]
RIght we have it at http://coala.readthedocs.io/en/latest/Users/Docker_Image.html - mind making a PR to add it to the readme or should we do it?

**Comment by jayvdb** [comment]
I'd like to add Travis *& Appveyor?) to that section of the docs, and can also do a PR here as you suggest.

**Comment by sils** [comment]
:+1: awesome - thanks. https://github.com/coala-analyzer/documentation/

**Comment by jayvdb** [comment]
I tried setting it up on Travis, and failed.

https://travis-ci.org/jayvdb/cws/builds/158663310

@abdealijk, can you see what I did wrong?

**Comment by sils** [comment]
Can you give the related code? That job shows success for me but doesn't do anything with the image.

**Comment by sils** [comment]
found it, https://github.com/jayvdb/cws/compare/9a6effa5c918...b58b85cbf833

**Comment by sils** [comment]
Apparently the `-d` flag is making docker exit and run it as a daemon, removing that might help @jayvdb

**Comment by sils** [comment]
Also your code isn't in the container :) you're not copying your files in.

**Comment by sils** [comment]
CC @underyx

**Comment by sils** [comment]
Try this: `docker run -v $(pwd):/app -w /app coala/base:0.8 coala-ci`

**Comment by sils** [comment]
You shouldn't need to pull the image, just running it should pull it implicitly if needed.

**Comment by jayvdb** [comment]
Thx. Will try it soon.
