### ISSUE TITLE
master bears

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#17]
It would be useful to have a Docker image that contains the latest bears, to be able to easily check if a bug has been fixed.

Or, it would be useful to pre-install the latest `requirements.txt` , and then downgrade if necessary.
e.g.

``` diff
 RUN git clone https://github.com/coala-analyzer/coala-bears.git
 WORKDIR /coala-bears
+RUN pip3 install -r requirements.txt
 RUN git checkout release/0.8
 RUN pip3 install -r requirements.txt
 RUN pip3 install -r test-requirements.txt
 RUN pip3 install -e .
 WORKDIR /
```

Then it is quicker to upgrade the bears, e.g. using

```
docker run --volume=$(pwd):/app --workdir=/app coala/base bash -c 'pip3 install -U git+https://github.com/coala-analyzer/coala-bears; coala-ci'
```

**Comment by sils** [comment]
We have a pre tag somewhere which should give you what you need

**Comment by sils** [comment]
it's not automatically built though. Instead of installing from git you can just `pip install coala-bears -U --pre` as we automatically do prereleases from master.

**Comment by sils** [comment]
Seen also https://github.com/coala-analyzer/docker-coala-base/issues/18 which even affects the release build, seems as if something broke in julia or changed.

**Comment by jayvdb** [comment]
Using `--pre` doesnt change this issue.  The problem is that the latest bears (master/pre-release) has lots of additional dependencies that are not installed into the Docker image.

**Comment by sils** [comment]
I think @fneu is working on this.

**Comment by fneu** [comment]
@jayvdb I've just not had the time lately to update the image. Due to dockers build time and memory requirements that process is not always straight forward. The python requirements are updated since I take the latest `requirements.txt`, but unfortunately I've not gotten the gemfile or npm requirements to work, so it needs manual labor for now.

After my exam on Thursday I might commit a day or two to update the images, I'd also take pull requests ;) 

In the long run I have hopes for cib to automate most things besides julia

**Comment by jayvdb** [comment]
As an example of what I am hoping for, I have a bug fix for https://bitbucket.org/birkenfeld/pygments-main/issues/1286 .  I want to test it.
So I run this docker on a project with lots of tabs, with my branch of pygments, but it fails due to no `hg`.

``` bash
$ docker run --volume=$(pwd):/app --workdir=/app coala/base bash -c 'pip3 install -U "hg+https://bitbucket.org/jayvdb/pygments-main@relative-tabs-test" "git+https://github.com/jayvdb/coala@ilab"; coala-ci'
Collecting hg+https://bitbucket.org/jayvdb/pygments-main@relative-tabs-test

  Cloning hg https://bitbucket.org/jayvdb/pygments-main (to revision relative-tabs-test) to /tmp/pip-7mhdzxus-build

  Error [Errno 2] No such file or directory: 'hg' while executing command hg clone --noupdate -q https://bitbucket.org/jayvdb/pygments-main /tmp/pip-7mhdzxus-build

Cannot find command 'hg'
```

 I've submitted #19 to fix this.

If I need to test master of coala-bears (or a dev branch), there are extra dependencies that need to be installed.

``` diff
$ git diff release/0.8..master -- requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 1d0038a..6feea7e 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,5 @@
 # Use >= for development versions so that source builds always work
-coala>=0.8.1
-setuptools>=19.2
+coala>=0.9.0.dev20160916100340
 munkres3==1.*
 pylint==1.*
 language-check==0.8.*
@@ -10,7 +9,7 @@ autoflake==0.6.*
 restructuredtext_lint==0.14.*
 proselint==0.3.*
 cpplint==1.*
-yapf==0.10.*
+yapf==0.11.*
 isort==4.*
 html-linter==0.3.*
 # Do *not* use 0.3 which is not backwards compatible to common clang versions
@@ -23,10 +22,10 @@ cppclean==0.9.*
 pydocstyle==1.*
 cmakelint==1.*
 vim-vint==0.3.*
-# Stable version 3.2 is problematic in Windows.
-# Use >=3.3,==3.* once nltk-3.3 is released.
-nltk==3.1.*
+nltk==3.2.*
 appdirs==1.*
 pyyaml==3.*
 vulture==0.10.*
+nbformat>=4.*
 pyflakes==1.2.*  # Although we don't need this directly, solves a dep conflict
+scspell3k==2.*
```

These can be pre-installed, and cached, so the Docker image is ready to switch to the master branch.

**Comment by sils** [comment]
@fneu ping
