### ISSUE TITLE
Tumbleweed breakage: libopenssl1

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#178]
```
Problem: python-2.7.13-2.2.x86_64 requires libcrypto.so.1.0.0(OPENSSL_1.0.0)(64bit), but this requirement cannot be provided

  uninstallable providers: libopenssl1_0_0-1.0.2k-1.2.x86_64[oss]

 Solution 1: downgrade of libopenssl1_0_0-1.0.2k-3.1.x86_64 to libopenssl1_0_0-1.0.2k-1.2.x86_64
 Solution 2: do not install python-2.7.13-2.2.x86_64
 Solution 3: break python-2.7.13-2.2.x86_64 by ignoring some of its dependencies
```
https://travis-ci.org/coala/docker-coala-base/builds/234965756

If the python2 dependencies are removed, the same occurs for python3

```
Problem: devscripts-2.15.1-1.9.x86_64 requires /usr/bin/python3, but this requirement cannot be provided

  uninstallable providers: python3-base-3.6.1-1.2.i586[oss]

                   python3-base-3.6.1-1.2.x86_64[oss]

 Solution 1: downgrade of libopenssl1_0_0-1.0.2k-3.1.x86_64 to libopenssl1_0_0-1.0.2k-1.2.x86_64
 Solution 2: install python3-base-3.6.1-1.2.i586 despite the inferior architecture
 Solution 3: do not install devscripts-2.15.1-1.9.x86_64
 Solution 4: break devscripts-2.15.1-1.9.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/4/c] (c): c
```
https://travis-ci.org/jayvdb/docker-coala-base/builds/236192952

When python3 is removed, php7 has the same problem:

```
Problem: php7-xmlwriter-7.1.5-1.2.x86_64 requires php7 = 7.1.5, but this requirement cannot be provided

  uninstallable providers: php7-7.1.5-1.2.i586[oss]

                   php7-7.1.5-1.2.x86_64[oss]

 Solution 1: Following actions will be done:
  do not install php7-xmlwriter-7.1.5-1.2.x86_64
  do not install php7-tokenizer-7.1.5-1.2.x86_64
  do not install php7-imagick-3.4.3-1.1.x86_64
  do not install php7-dom-7.1.5-1.2.x86_64
  do not install php7-pear-Archive_Tar-7.1.5-1.2.noarch
 Solution 2: downgrade of libopenssl1_0_0-1.0.2k-3.1.x86_64 to libopenssl1_0_0-1.0.2k-1.2.x86_64
 Solution 3: install php7-7.1.5-1.2.i586 despite the inferior architecture
 Solution 4: break php7-xmlwriter-7.1.5-1.2.x86_64 by ignoring some of its dependencies
```
https://travis-ci.org/jayvdb/docker-coala-base/builds/236195585

**Comment by jayvdb** [comment]
Created https://bugzilla.opensuse.org/show_bug.cgi?id=1040862 and https://bugzilla.opensuse.org/show_bug.cgi?id=1040863

**Comment by yash-nisar** [comment]
Getting package not installed errors : 
```
error: package libasan3 is not installed
error: package libxslt-tools is not installed
error: package python-javapackages is not installed
error: package python-pyxb is not installed
```
See https://travis-ci.org/yash-nisar/docker-coala-base/builds/240685648

**Comment by jayvdb** [comment]
ok, wow, yes, it looks like this bug has been fixed upstream and you have a different problem (and it is a common problem that we have to fix on our side fairly regularly .. please create a new issue and work on it).

This is strange because https://bugzilla.opensuse.org/show_bug.cgi?id=1040863 is still open, and the mentioned https://build.opensuse.org/request/show/498922 is still open, and https://software.opensuse.org/package/openssl still says Tumbleweed is openssl `1.0.2k` and not `1.0.2l`.

**Comment by yash-nisar** [comment]
Which implies we close this issue ? @jayvdb

**Comment by jayvdb** [comment]
I need to notify upstream first, after I verify the problem is voodoo fixed (and possibly try to find what changed to fix it.).

**Comment by yash-nisar** [comment]
Another build failure -> https://travis-ci.org/yash-nisar/docker-coala-base/builds/240701021

**Comment by jayvdb** [comment]
Please do not report other unrelated problems here (try to understand them first, so you can create good bugs about them).

**Comment by yash-nisar** [comment]
Alright, doing them after creating a new issue, I've tried a possible patch. Lets see if the voodoo works !

**Comment by jayvdb** [comment]
Closed upstream.
