### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by sils** [coala/docker-coala-base#18]
@fneu I can't build the doker imgae. this sucks, we just had a release.

**Comment by sils** [comment]
`Build failed: The command '/bin/sh -c julia -e "Pkg.add(\"Lint\")"' returned a non-zero code: 1`

**Comment by fneu** [comment]
fixed

**Comment by jayvdb** [comment]
ae7b5f622b6ec was the fix, and now the same problem exists in a different form: https://github.com/coala/docker-coala-base/issues/35

Also noting https://github.com/coala/coala-bears/issues/859 was a problem with Julia Lint around that same time.
