### ISSUE TITLE
NPM error: Cannot find module 'node-fetch-npm'

### ISSUE THREAD

**Issue by yash-nisar** [coala/docker-coala-base#182]
See https://travis-ci.org/yash-nisar/docker-coala-base/builds/240772147#L2027-L2059 for a verbose output.

**Comment by jayvdb** [comment]
Try installing a lower version of npm.

**Comment by yash-nisar** [comment]
@jayvdb Tried downgrading npm but didn't work. We're using npm `5.0.0` and node `8.0.0`. How do I install a lower version of npm ?

**Comment by jayvdb** [comment]
> Tried downgrading npm but didn't work.

What did you try.  Show me a build log , or give a technical description of what you tried.

> How do I install a lower version of npm ?

What command is currently installing npm?

**Comment by yash-nisar** [comment]
`Installing: npm8-8.0.0-3.1.x86_64 [............done]` is currently getting installed.

Tried doing `npm install -g npm@latest-4`, build log -> https://travis-ci.org/yash-nisar/docker-coala-base/jobs/241315197

We have [these](https://github.com/coala/docker-coala-base/blob/master/Dockerfile#L62-L63) commands for the installation of `nodejs` and `npm`, but `npm` gets installed with `nodejs`.

**Comment by yash-nisar** [comment]
Tried removing `node_modules` and reinstalling according to [this answer](https://stackoverflow.com/questions/9023672/how-do-i-resolve-cannot-find-module-error-using-node-js) but that didn't work either, build log -> https://travis-ci.org/yash-nisar/docker-coala-base/builds/240768995

**Comment by jayvdb** [comment]
> We have these commands for the installation of nodejs and npm, but npm gets installed with nodejs.

Have you tried changing the zypper command to install a different node / npm?

**Comment by yash-nisar** [comment]
Yes, see https://travis-ci.org/yash-nisar/docker-coala-base/builds/241335590

**Comment by jayvdb** [comment]
As the log tells you, `nodejs=6.5.0` and `npm=3.10.3` are not valid package names for the `zypper` command. RTFM :P

**Comment by yash-nisar** [comment]
Fixed by using the lower version i.e. nodejs6. nodejs8 was installed earlier.
