### ISSUE TITLE
add go dependencies

### ISSUE THREAD

**Issue by sils** [coala/docker-coala-base#2]
@AbdealiJK can you help me getting all bear deps in this image?

**Comment by AbdealiLoKo** [comment]
My current computer cannot run docker (its 32bit).
I can look into it tomorrow when I go to my university

**Comment by sils** [comment]
I think the main thing is that we don't have something like a goopfile
anymore for go and stuff... ideally I wouldn't want to need to resync the
docker image manually

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-06 18:04 GMT+01:00 AbdealiJK notifications@github.com:

**Comment by AbdealiLoKo** [comment]
@sils1297 we can just make a goopfile but not use in circleci.
Circleci seems to have a problem with it, but it works on my local machine

**Comment by sils** [comment]
Have we identified the problem with the goop file? Can we maybe file an issue for that? It'd be way easier to manage deps that way...
