### ISSUE TITLE
requests vs urllib3 version conflict

### ISSUE THREAD

**Issue by co-robo** [coala/docker-coala-base#215]
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5972b2e42723db8d5e3576f4)

**Comment by jayvdb** [comment]
The source of the problem is https://github.com/coala/coala/issues/4512

Another potential approach is somehow telling pip to not upgrade urllib3 as it is unnecessary to do it in this case.

**Comment by jayvdb** [comment]
Note this has been solved in coala, but there is now https://github.com/coala/docker-coala-base/issues/216, and https://github.com/coala/coala/issues/4519 also blocking a green build , and of course https://github.com/coala/docker-coala-base/pull/214

**Comment by jayvdb** [comment]
Fixed upstream
