### ISSUE TITLE
JSComplexityBear broken

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#219]
`new_process_output() got an unexpected keyword argument 'cc_threshold'`

https://travis-ci.org/coala/docker-coala-base/builds/256537062

This may have been a hidden error, exposed by recent improvement to coala core testing, or maybe something more sinister.

**Comment by yash-nisar** [comment]
Shouldn't `coala-bears` be the right place for this issue ?

**Comment by jayvdb** [comment]
Possibly/probably, but this is a bug in the docker also.
An upstream bug in coala-bears needs to be created if that is where the bug is, or upstream in coala if that is where the problem is.
The last two big bugs in the docker have been in coala.

**Comment by yash-nisar** [comment]
Created an issue [here](https://github.com/coala/coala/issues/4576) which is the cause of the issue.
