### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by yash-nisar** [coala/docker-coala-base#220]
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
```
See https://travis-ci.org/coala/docker-coala-base/builds/256537062 for the complete log.
Upstream issue : https://github.com/coala/coala-quickstart/issues/143

upstream

**Comment by jayvdb** [comment]
Fixed upstream
