### ISSUE TITLE
Add coala-quickstart

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#25]
coala-quickstart needs to be added after https://github.com/coala/coala-quickstart/issues/39 is ready, so that https://github.com/coala/coala/wiki/Google-Code-In-Task-Use-coala does not need a "Create .coafile" section, which will trip up many newbies, and instead `coala-quickstart` can be used , and will lead to many improvements in the automatic mode, which is often going to de-activate bears for reasons that we need to analyse and fix.

**Comment by Mixih** [comment]
This issue is ready for work
