### ISSUE TITLE
Ruby gem list is not automatic

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#27]
There is a static list of gems in the Dockerfile:
```Dockerfile
RUN gem install rubocop sqlint scss_lint reek && ...
```

[CSVLintBear](https://github.com/coala/coala-bears/blob/master/bears/csv/CSVLintBear.py) was added recently, but is not available yet in the Docker image.

The list of gems to install could be easily taken from:
https://github.com/coala/coala-bears/blob/master/Gemfile

This repo could even have coala-bears as a sub-module, use the actual `Gemfile`, and `requirements.txt` , etc.

**Comment by SanketDG** [comment]
can't we just do `gem install` in the coala-bears dir? It would take the Gemfile as default.

**Comment by sils** [comment]
though be sure to not get the gemfile from master for the release branches of this image

**Comment by fneu** [comment]
This should be possible for `gem` and `npm` packages, since we clone the correct repo anyways. Hence the fixme comments. I'm not sure why this didn't work out for me initially, but there were some dependency fuck-ups IIRC. I also don't think the symlinks should be necessary...

**Comment by jayvdb** [comment]
> can't we just do gem install in the coala-bears dir? It would take the Gemfile as default.

Ya, that is roughly what I had in mind, but was thinking sub-modules.  The existing clone of coala-bears is effectively the same thing.
