### ISSUE TITLE
Use master for pre-release

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#32]
From https://github.com/coala/docker-coala-base/pull/30#issuecomment-261708802 , @sils wrote

> Ideally we shift the latest tag to the latest release and maintain the prerelease on master so changes like this are possible in the future.

**Comment by jayvdb** [comment]
@fneu, can this be sorted out as a matter of urgency.  We need to build a docker for 0.9, and add extra linters and binaries, and currently I dont know where to send PRs.

**Comment by jayvdb** [comment]
The [GCI tasks](https://github.com/coala/coala/wiki/Google-Code-In) depend on this; they will be in high usage from 28 November onwards.

**Comment by fneu** [comment]
Yes sure and this makes complete sense, as previously the latest release branch mirrored master.

**Comment by jayvdb** [comment]
Who can **do** this??  We need a 0.9 docker image *now*, so we can test it before GCI.
At the moment we have two branches diverging, and I dont know which branch to send patches to.

**Comment by jayvdb** [comment]
I believe this has now been fixed? And we PR to master?

**Comment by sils** [comment]
Yes, PR to master. Also make a PR from master to release/0.9 when
appropriate
