### ISSUE TITLE
Install expect into the image

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#33]
`coala` has many questions. `expect` can answer them.

difficulty/newcomer

**Comment by jayvdb** [comment]
e.g. something like `expect -c 'spawn coala --apply-patches --no-orig; expect Ctrl-D; send 0'`
(needs improvement, and should be documented also)

**Comment by Mixih** [comment]
@jayvdb I'm not quite sure why we need this. Aren't the coala configs and noninteractive mode sufficient?
edit: gotcha, those features are incomplete
