### ISSUE TITLE
Make cache NLTK data one command

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#34]
The NLTK data should be cached in the Docker.

See https://github.com/coala/coala/pull/3082 for roughly what is needed.

**Comment by Mixih** [comment]
May or may not be present. Need more testing to verify...

**Comment by Mixih** [comment]
Might as well add it anyways as it can't hurt?

**Comment by jayvdb** [comment]
Correct

**Comment by jayvdb** [comment]
Ah, already done
```
# Nltk data
RUN python3 -m nltk.downloader punkt
RUN python3 -m nltk.downloader maxent_treebank_pos_tagger
RUN python3 -m nltk.downloader averaged_perceptron_tagger
```

Could speed that up by invoking as one command.
