### ISSUE TITLE
Add approved label

### ISSUE THREAD

**Issue by Mixih** [coala/docker-coala-base#54]
CC @sils . Also we could use some of the other labels

**Comment by jayvdb** [comment]
See https://github.com/coala/coala/issues/3026

**Comment by sils** [comment]
@Mixih you should be able to set the labels by yourself FWIW

**Comment by sils** [comment]
added the label

**Comment by Mixih** [comment]
Whoops, though you needed to be admin to do that :(. sorry I bothered you.

**Comment by sils** [comment]
no issue

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/
