### ISSUE TITLE
Docker images are not being automatically updated

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#63]
The org name change from `coala-analyzer` to `coala` broke updated rebuilds.

We should have rebuilds after changes to this repository.

We should also have rebuilds after changes to coala-bears , and less important are changes to coala.
Triggering a rebuild daily should be sufficient.

This is critical for GCI, as people need to be able to add/fix bears and be able to use them.

**Comment by jayvdb** [comment]
@sils, you are assigned because I  do not appear to be able to do this.

When I connect to GitHub using [Settings](https://cloud.docker.com/app/coala/settings/) shows GitHub "Account" is jayvdb .

Then on [automated builds](https://cloud.docker.com/app/coala/repository/docker/coala/base/builds/edit), "Source Repository" , "Select organisation" does not list coala for me -- it lists orgs where I am an owner.

Also on [create](https://cloud.docker.com/app/coala/repository/create), I only see my orgs, not 'coala'.

**Comment by sils** [comment]
Ah, I didn't see this. Does that mean you can't even trigger builds?

**Comment by sils** [comment]
Oh I never used "docker cloud" figuring my way around right now, had it on hub.docker.com before.

**Comment by sils** [comment]
![dockerbuildrules](https://cloud.githubusercontent.com/assets/5716520/21622627/c9b1a03a-d1fe-11e6-973f-58e8b72991a8.png)

This is the setup now.

**Comment by sils** [comment]
So this seems to work, I even get a docker cloud build state on my PR 👍  closing this for now, let's reopen if something's wrong or make a new issue.

**Comment by fneu** [comment]
looks good

**Comment by jayvdb** [comment]
> Does that mean you can't even trigger builds?

I can now.  Looks good.
