### ISSUE TITLE
cppcheck bear not available

### ISSUE THREAD

**Issue by stefanoco** [coala/docker-coala-base#7]
It seems that CPPCheckBear is not available in the docker image.

**Comment by sils** [comment]
Hey @stefanoco thanks for this report. @fneu didn't you want to have a PR ready yesterday adding the missing deps?

**Comment by sils** [comment]
this should be fixed, IIUC you're just trying it out, close this if it works.

@fneu your PR is still due, what happened?

**Comment by fneu** [comment]
CPPCheckBear is not available because it is not part of coala-bears 0.2.0.

It is now available on the `pre` branch and will be available on master after the next release of coala and coala-bears.
