### ISSUE TITLE
DNS settings for Docker

### ISSUE THREAD

**Issue by stefanoco** [coala/docker-coala-base#9]
While using this Docker image for GitLab CI integration I realized that a tricky issue can arise in this setup, while using a private GitLab repo, which is fairly common for closed development.

Not directly related to this image but a short note can save time here: when using a Docker image for GitLab CI build, the runner will start a new container and from inside the container a `git clone` command is the first operation. So from inside the container the GitLan server shoudl be reachable by URI, but sometime the container is not accessing the right DNS service (long story here...) so that a suitable configuration should be applied to the runner by modifying its `config.toml` file (usually found inside `/etc/gitlab`).

**Comment by sils** [comment]
Also we probably want to  have a documentation page about the docker image and the editor plugins in general.

**Comment by sils** [comment]
CC @fneu for docker issues

**Comment by sils** [comment]
@stefanoco I currently don't fully understand the issue, would you mind writing this down as a small paragraph we can include in the documentation? I can take care of making it a commit, attribute it to you and get it through QA. (You can do it yourself as well if you want of course but I understand time is an issue.)

**Comment by stefanoco** [comment]
Sure I'm writing a note about this in a comment here. As you said time is an issue and I'm currently not a regular contributor to GH projects like this one but I promise I'll try to, because we're seriously starting using coala in my company.

**Comment by stefanoco** [comment]
A coala-analyzer docker image is useful when automating a check withing a GitLab CI assisted workflow. In a properly configured GitLab CI setup (please see related documentation [here](http://docs.gitlab.com/ce/ci/)), the server will try to execute the requested operations in a runner environment by first [starting a specified docker image](http://docs.gitlab.com/ce/ci/docker/using_docker_images.html).

The coala-analyzer docker image is the one you want to specify while performing some static code check with GitLab CI. In this (and similar ones) situation you could face an issue with name resolution of your GitLab CI server. Please keep in mind that the GitLab runner running on the delegated host will try to clone the repository as a first task; when working with a docker image, this task is being performed from inside the image itself. So prerequisites for this to be successful are:
1. git is available inside the image
2. GitLab CI server name is resolved and reached from inside the image

While the first requirement depends in the docker image composition (and satisfied by coala-analyzer image) the second can be tricky due to how docker builds the networking environment of a running container. Not going into much details, it's important to note here that a container will inherit the DNS related properties from the host where it's being launched in. So depending on where the GitLab CI runner is being installed, situations might exist where a coala-analyzer container is not able to clone the repository due to the GitLab server name not being resolved. More frequently than while using the public GitLab instance, this can happen with private repository and internal DNS setups (for instance when using [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) as a tool in the same host).

When this is the case the most straightforward workaround is to add a configuration line inside the `config.toml` [configuration file for the `gitlab-ci-multi-runner` runner](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/configuration/advanced-configuration.md):

`
  extra_hosts = ["my-gitlab.example.com:192.168.0.100"]
`

Please be aware that the more generic `dns` setting listed in the `gitlab-ci-multi-runner` documentation has been recently added and at the time of this writing is not available in official builds.

**Comment by sils** [comment]
That was quick, thanks! I'll look to it that it gets added to the docs.

**Comment by sils** [comment]
@stefanoco hm, that sounds like we should rather fix that in our image itself so users don't need to bother with it at all?

**Comment by sils** [comment]
CC @fneu how is the work on the new image going? We could preconfigure it like that since GitLab CI is indeed one main usecase!

**Comment by sils** [comment]
Ah I didn't read it completely, @stefanoco but then IIUC this issue has nothing to do with our image and would occur with any other image as well, right?

**Comment by sils** [comment]
I'm compressing the docs a bit because I'm always afraid that most people will just not read docs if they're long.

**Comment by stefanoco** [comment]
Yes that's correct it does not depend on this particular image but using gitlab CI with docker for static code check is rather typical so this issue should be mentioned IMO. Ok for compressing as you like of course
